# Numpy Basics

In [ ]:
import numpy as np

#creating different arrays
arr1 = np.array([1,2,3,4])      #from python list
arr2 = np.zeros((2,3))          #2x3 arrays of zero
arr3 = np.ones((3,3))           #3x3 array of one
arr4 = np.arange(0,11,2)       # arrange array that is from 0 to 11 and take 2 steps
arr5 = np.linspace(0,1,5)       # take 5 numbers between 0 and 1

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 0  2  4  6  8 10]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#array properties
arr = np.array([[[1,1],[2,2],[3,3]]])
print("Shape=",arr.shape)      #shape of the array rows and columns in the output the 1 shows layer 3 shows rows and 2 shows columns
print("Dimensions=",arr.ndim)  # shows the dimension of the array
print("Size=",arr.size)        # prints how many elements are there in the array

Shape= (1, 3, 2)
Dimensions= 3
Size= 6


In [ ]:
#indexing
print(arr)
print(arr[0,2,0]) # first 0 means layers 2 means 3rd row and 0 means column
print(arr[:, 1])  # all layers and 2nd row
print(arr[0, :])  # first layer and all rows

[[[1 1]
  [2 2]
  [3 3]]]
3
[[2 2]]
[[1 1]
 [2 2]
 [3 3]]


In [ ]:
# mathematical operations
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[4,5,6],[4,5,6]])

print(a+b) #addition
print(a-b) #Subtraction
print(a*b) #multiplication
print(a/b) #division
print(np.dot(a,b.T)) #dot product also we took transpose of b
# Random numbers
print(np.random.rand(2,5)) #printing random numbers 2 rows and 5 columns

[[5 7 9]
 [5 7 9]]
[[-3 -3 -3]
 [-3 -3 -3]]
[[ 4 10 18]
 [ 4 10 18]]
[[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]]
[[32 32]
 [32 32]]
[[0.0639735  0.31234727 0.33301946 0.10952572 0.52329409]
 [0.28429898 0.26894581 0.8810353  0.08714112 0.05657875]]


In [ ]:
# reshaping arrays
arr = np.arange(12)
print(arr.reshape(4,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Numpy self practice

In [ ]:
# import numpy library
import numpy as np

In [ ]:
#array of 6 elements
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
a = np.arange(6)
print(a)
print(a.shape) # shows rowns and columns

[0 1 2 3 4 5]
(6,)


In [ ]:
q_2 = a[np.newaxis, :] #gives a a new dimension to the existing set
print(q_2)
print(q_2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [ ]:
# create array
arr1 = np.array([1,2,3,4,5,6]) # 1Dimension array
arr2 = np.array([[1,2,3],[4,5,6]]) # 2Dimension array
print("1D array:",arr1.shape)
print(arr1)
print("2D array:",arr2.shape)
print(arr2)

1D array: (6,)
[1 2 3 4 5 6]
2D array: (2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
# checking type
type(arr1)

numpy.ndarray

In [ ]:
# initialize a zero array
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# initializing a ones array
one = np.ones((2,3))
one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# full array
full = np.full((2,3),2) # this shows that the array is 2x3 and all the values are supposed to be 2
full

array([[2, 2, 2],
       [2, 2, 2]])

In [ ]:
# checking the datatype of full
full.dtype

dtype('int64')

In [ ]:
# type
type(full)

numpy.ndarray

In [ ]:
# making an identity matrix
identity = np.eye(3) # 3x3 identity matrix
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# data type
identity.dtype

dtype('float64')

In [ ]:
#type
type(identity)

numpy.ndarray

# Attributes of array

In [ ]:
# Shape of array
identity.shape

(3, 3)

In [ ]:
# length of array
len(identity)

3

In [ ]:
# dimension of the array
identity.ndim

2

In [ ]:
# size of the array
identity.size

9

In [ ]:
# most of the operations are done above the left are done here
a=np.arange(5)
b=a**2 # element wise squaring
print(b)

[ 0  1  4  9 16]


In [ ]:
# empty array
empty = np.empty((2,3))
print(empty)

[[0.00e+000 4.94e-324 1.98e-323]
 [4.45e-323 7.91e-323 1.24e-322]]


In [ ]:
# access first row
print(empty[0])

[0.e+000 5.e-324 2.e-323]


In [ ]:
# arrange the array from 6 to 18 and take 2 steps
np.arange(6,18,2)

array([ 6,  8, 10, 12, 14, 16])

In [ ]:
# array of odd numbers
odd_numbers = np.arange(1,20,2) # it goes from 1 to 20 and takes 2 steps at a time
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# difference between numbers
difference = np.arange(1,20,0.5) # takes numbers from 1 to 20 and takes a step of 0.5
print(difference)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [ ]:
#linespace (linear trends # between two numbers)
lin = np.linspace(1, 10, 5) # the numbers are from 1 to 10 and we need to take 5 steps at a time
print(lin)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
lin = np.linspace(0, -10,5, endpoint=False)
print(lin)

[ 0. -2. -4. -6. -8.]


In [ ]:
# specify datatype of array
x = np.array([1,2,3,4,5,6],dtype=np.float64) # 1D array with float64 datatype
print(x)


[1. 2. 3. 4. 5. 6.]


In [ ]:
y = np.arange(6, dtype=np.int64) #0D array with int64 datatype
print(y)

[0 1 2 3 4 5]


In [ ]:
# sort an array
sorted_array = np.sort(y)
print(sorted_array)

[0 1 2 3 4 5]


In [ ]:
# concatenate arrays
a = np.array([1,2,3])
b= np.array([4,5,6])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [ ]:
# concatenate arrays
x = np.array([[1,2,3],[4,5,6]])
y= np.array([[7,8,9]])
z = np.concatenate((x,y), axis=0)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# concatenate arrays
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[7,8,9],[1,2,3]])
k = np.concatenate((i,j),axis=0)
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [ ]:
# 3d array
l = np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[10,11,12]],
             [[13,14,15],[16,17,18]]]
)
print(l)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
len(l)

3

In [ ]:
l.shape

(3, 2, 3)

In [ ]:
l.size

18

In [ ]:
#reshape array
n= np.array([1,2,3,4,5,6,7,8,9,10,11,12]) #1d array
m = np.reshape(n,(3,4)) # reshape into 3 rows and 4 columns
print(m)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# reshaping
np.reshape(l,(3,3,2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
# convert into 2d array
l_2d = l.reshape(-1,2) # this makes sure that the row size becomes default that is 1 and column size becomes 2
print(l_2d)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]]


In [ ]:
# indexing and slicing
a = np.array([1,2,3,4,5,6])
#accessing elements
print(a[0]) # first element
print(a[1]) # second element
print(a[-1]) # last element
# slicing
print(a[1:4]) # printing elements from index 1 to 3(exclusive of 4)
print(a[:3]) # printing the first 3 elements
print(a[3:]) # printing elements from index 3 to the end
# Boolean indexing
b = a > 3 # boolean array where elements are greater then 3
print(b)

1
2
6
[2 3 4]
[1 2 3]
[4 5 6]
[False False False  True  True  True]


In [ ]:
# using 2 conditions
result = (a>3) & (a<6)
print(result)
print(a[result])

[False False False  True  True False]
[4 5]


In [ ]:
a[(a>3)&(a<6)]   # Elements greater than 3 and less than 6

array([4, 5])

In [ ]:
a[(a>3)&(a<6) & ( a % 2 == 0) ]

array([4])

In [ ]:
a[(a > 3) | (a < 6)] # since the boolean operation is true all the elements will be printed

array([1, 2, 3, 4, 5, 6])

In [ ]:
# creating array from an existing one
a = np.array([1,2,3,4,5,6])
b = a.reshape((2,3))
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# making an array from data elsewhere
a = np.arange(50)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
# taking some elements
arr1 = a[20:45]
print(arr1)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44]


In [ ]:
# stacking the arrays
b = np.array([1,2,3,4,5,6])
c = np.array([7,8,9,10,11,12])
d = np.vstack((b,c)) # stacking vertically
print(d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#stacking horizontally
d = np.hstack((b,c))
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# reshaping
d = d.reshape((3,4))
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Matrix or matrices

In [129]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [131]:
b = np.arange(0,50,2).reshape(5,5)
print(b)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [132]:
b[:,:] # all rows and all columns

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [133]:
b[1:,:] # all rows except first and all the columns

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [134]:
b[1:3,:] #select rows from index 1 to 3(3 is not included) and all the columns

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [135]:
b[1:3,2:] #select columns from 2 till end and rows from index 1 to 3

array([[14, 16, 18],
       [24, 26, 28]])

In [136]:
# slicing a matric
c=b[1:3,3:5]
print(c)

[[16 18]
 [26 28]]


In [137]:
# getting max
c.max()

np.int64(28)

In [138]:
#getting min
c.min()

np.int64(16)

In [139]:
#getting sum
c.sum()

np.int64(88)

In [140]:
c.max(axis=1) # max column

array([18, 28])

In [141]:
c.min(axis=0) # min colum

array([16, 18])

In [142]:
m = np.arange(0,50,5).reshape(5,2)
m

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [143]:
m + np.array([2, 5])

array([[ 2, 10],
       [12, 20],
       [22, 30],
       [32, 40],
       [42, 50]])

In [144]:
np.vstack(m + np.array([2, 5])) #stacked vertically

array([[ 2, 10],
       [12, 20],
       [22, 30],
       [32, 40],
       [42, 50]])

In [145]:
np.hstack(m + np.array([2, 5])) #stacked horizontally

array([ 2, 10, 12, 20, 22, 30, 32, 40, 42, 50])

In [146]:
#generate randmom numbers
import random
random_numbers = [random.randint(1,100) for i in range(10)]
print(random_numbers)

[56, 48, 35, 96, 79, 79, 66, 16, 85, 23]
